### PR TITLE
Import visible tags from CubeTutor.

### LINKED ISSUE #710: Import tags and colors from CubeTutor

### PR DESCRIPTION
**Pull request by phulin**
Fixes #710.

### CODE REVIEW

**Comment by dekkerglen** [comment]
Note: this only works for visible tags, it will not work for tags that have been assigned a color on CT

**Comment by phulin** [comment]
True

**Comment by dekkerglen** [comment]
This PR is currently failing the prettier check

**Comment by phulin** [comment]
I think that’s all in files i didn’t modify but i can merge in master if you want

**Pull request merged**
