### PR TITLE
Refactor cube_routes.js.

### PR DESCRIPTION
**Pull request by phulin**
This PR breaks out some of the routes in cube_routes into two separate files.

### CODE REVIEW

**Comment by dekkerglen** [comment]
I believe the change to util: line 71 is erroneous, was this bugged before?

**Comment by phulin** [comment]
Yes, that's a bug, although it doesn't necessarily need to be in this PR and I haven't seen it actually cause any issues. See the cube.cards schema in `models/cube.js`; it's supposed to be type_line.

**Comment by phulin** [comment]
Will update to no longer conflict.

**Comment by phulin** [comment]
Closing this for now, may reopen later

**Pull request closed without merging**
