### PR TITLE
inital setup of prettier and eslint using airbnb standards

### PR DESCRIPTION
**Pull request by joshfinnie**
This is the start of getting `prettier` and `eslint` set up for CubeCobra.

I went through `app.js` to show some of the changes that would be required to get a sense of them.

### CODE REVIEW

**Comment by phulin** [comment]
This looks really great. I assume we need a second commit making all the changes in the rest of the codebase?

**Comment by joshfinnie** [comment]
@phulin yea, we can either make a massive update or we can just submit these rules and have the developers start implementing the changes on PRs for other work.

**Comment by phulin** [comment]
My instinct is that we want one massive PR that also puts it into the checks that Travis runs.

**Comment by joshfinnie** [comment]
@dekkerglen this is ready for merger

**Pull request merged**
