### PR TITLE
custom image urls

### PR DESCRIPTION
**Pull request by emmett9001**
This pull request addresses part of https://github.com/dekkerglen/CubeCobra/issues/57 by adding support for custom card image URLs. Every card may have an optional image URL associated with it. If configured for a card, this image will display everywhere the card would display within the app. URLs that either point to broken images or non-image resources are handled with a `background-image` CSS property of a Magic card back. Custom images can be set one card at a time using the modal editing interface. The custom image can be cleared for a card by clearing the Image URL input field in this modal and saving.

I've tested this change extensively on my local machine, but it's far-reaching enough that it's certainly possible I've missed some edge cases. Please point those out as you see them via comments, and I'll address them.

The approach of allowing external image URLs was chosen primarily because it allows custom image configuration, a widely-requested feature, to be released before the complex issue of image uploading and storage is resolved. Additionally, the majority of changes in this pull request apply to both the unhosted and the hosted implementation, which means that most of the effort put toward this change does not become "wasted" when image hosting is implemented.

This change was made with an eye toward compatibility with a future image hosting implementation, and has a clear migration path both for initial deployment and for updating to hosted images. When this change is first deployed, all cubes without custom images configured (all cubes) will be unaffected. Users can "opt in" to using custom images by configuring them on a per-card basis. When image hosting is deployed atop this change, configured external images will not need to be overwritten on deploy. The newly added `imgUrl` database field can be overwritten when an image is uploaded, and the behavior implemented in this pull request will cause those uploaded images to display properly.

Some miscellaneous notes on the implementation:
* Cards with URL that point to invalid images don't get autocard hover images. This indicates the broken state of the URL to the user while also sidestepping the annoying problem of making it work properly.
* Custom images are not included in blog posts.
* Flip cards show their normal, non-custom back side.
* Custom images are excluded from group edits. This is because the use case of assigning the same image to multiple cards is not something I chose to support in this pull request.
* There has been some debate in the Discord about whether to stretch or letterbox images that are not the same aspect ratio as Magic cards. This pull request chooses to stretch them.

Overview of changes
* Adds the `imgUrl` String field to the Cube database model
* Adds a default Magic card back image to `public/content`
* Adds some CSS rules implementing a class that defaults missing card images to the Magic card back using `background-image`
* Changes most uses of `card.details.image_normal` to `card.details.display_image`
* Adds logic to context modal submission causing `null` to be sent as the value of an update field when the image URL is unset
* Sets `card.details.display_image` as `imgUrl` if defined, `card.details.image_normal` otherwise
* Adds a Card Image URL field to the modal edit screen and populates it with `imgUrl` if specified
* Adds `util.getCardImageURL` as a convenience function implementing image precedence
* Adds a wrapping `<div>` around each card in the visual spoiler to allow placeholder images to align properly

Here is a screenshot of a visual spoiler using this functionality. Note that although the custom images configured in this screenshot depict unofficial Magic cards, this pull request does not address the issue of "custom cards", covered in https://github.com/dekkerglen/CubeCobra/issues/124. These images were chosen for the screenshot because they are clearly non-default images that are also the same shape as a Magic card.
Screenshot from 2019-09-05 17-02-35

### CODE REVIEW

**Comment by omniczech** [comment]
Should allow users to disable custom images when viewing cubes.

**Comment by lane-eden** [comment]
if the image url breaks can we just show the original card art? It would be lame to go into someone’s cube that they haven’t maintained and see a bunch of card backs

**Comment by emmett9001** [comment]
An implementation of custom art toggle for cube viewers as @omniczech mentioned also solves the issue @lane-eden brought up. For a cube with unmaintained, broken images, the viewer can toggle custom images off to fix the viewing experience.

Defaulting broken images to the normal image has the issue of not providing clear feedback to the editing user, since a failed edit can appear to have had no effect.

I’m not sure whether allowing the toggle should block this pull request or be opened as a separate issue post-merge.

**Comment by emmett9001** [comment]
Considering the above a bit more, I believe it's acceptable to merge this without support for the custom image toggle and to open a separate issue for that feature.

**Comment by emmett9001** [comment]
Opened an issue to track the custom image toggle https://github.com/dekkerglen/CubeCobra/issues/279

**Pull request merged**
