### PR TITLE
Improving serverjs test coverage with GetTokens tests

### PR DESCRIPTION
**Pull request by anderoonies**
I also separated the tests into suites to try to solve some async weirdness I was having with the persistent data structures that the suites share.

`cards_small.json` now has the ELD tokens

image

### CODE REVIEW

**Comment by dekkerglen** [comment]
Can you rebase and fix merge conflicts?

**Comment by anderoonies** [comment]
@dekkerglen sorry for being slow, rebased now

**Comment by anderoonies** [comment]
i will rebase this again after this weekend, i think i broke it with my other test updates

**Comment by dekkerglen** [comment]
Another PR has collided with this one again. Sorry :(

**Pull request closed without merging**
