### PR TITLE
Add JaceVP emblem

### LINKED ISSUE #966: Jace, Vryn's Prodigy emblem missing from tokens
At least in [my cube](https://cubecobra.com/cube/list/dillon), the generated tokens misses the emblem for Jace, Vryn's Prodigy. 

To reproduce, see here: https://cubecobra.com/cube/analysis/dillon?nav=tokens.

### PR DESCRIPTION
**Pull request by timfreilly**
fixed #966 Adds flip Jace's emblem to the special list of tokens.

### CODE REVIEW

**Comment by timfreilly** [comment]
Any idea why the build failed?

**Comment by dekkerglen** [comment]
> Code style issues found in the above file(s). Forgot to run Prettier?

Do `npm run beautify` to fix.

Also, is this case being missed by the parser, or are we just not parsing the back side of flip cards? If it's the latter, this isn't the correct fix

**Comment by timfreilly** [comment]
I looked at the other items in that exceptions list and a lot of them are for flip cards. There's a comment on line 142 talking about it:
  // the cards below are transform cards that are on here due to the way
  // we currently do not populate the oracle text of transform cards.

I was adding this one missing card to that list. Do you think the issue should be changed to  rewrite the code to understand flip cards?

**Comment by dekkerglen** [comment]
Yeah this is fine for now

**Comment by timfreilly** [comment]
Made it pretty

**Pull request merged**
