### PR TITLE
Fixed issue which caused peasant cube count to not display in card play rate analytics

### PR DESCRIPTION
**Pull request by danielprue**
Bug fix for #1598 

Previous behavior: Under the Play Rate tab of a card page, the peasant cube count always displays 0, even for cards that are in peasant cubes.

New behavior: Peasant category added in the cardhistories model. On the next card history update, the database will now populate with information about how many peasant cubes that card is in.

I also added behavior that will autodetect peasant cubes as cubes that are not pauper legal, but only contain common or uncommon cards and adds peasant to the type line. This is similar to logic that already exists for pauper cubes.

### CODE REVIEW

**Comment by dekkerglen** [comment]
BTW are you on discord? That's where most of the dev discussion occurs
https://discord.gg/36nfm8c

**Comment by danielprue** [comment]
Yep, I am on the discord already! This is the largest project I've worked on before, so I mostly lurk and and try to pick up some of the easier looking bug fixes, but I'll try to comment more in there as I get more comfortable with the project.

**Comment by dekkerglen** [comment]
Do you have the contributor role? That unlocks the dev channels

**Comment by danielprue** [comment]
Yep! My discord nickname should be set to the same as my github

**Pull request merged**
