### PR TITLE
Added api route to export cubes to JSON via API

### LINKED ISSUE #1514: JSON Export for cubes
Currently, a lot of information on cubes cannot be obtained through the API. This issue is for an API endpoint to get a JSON object back containing relevant cube info.

@dekkerglen raised the concern of throttling becoming necessary if this were to become implemented.

### PR DESCRIPTION
**Pull request by Likewise42**
Fixes #1514 

Simple PR to allow cube objects to be retrieved from an API call. @dekkerglen had concerns about throttling if this is added, so this PR can probably sit until that is implemented.

### CODE REVIEW

**Comment by dekkerglen** [comment]
Use the annotation "Fixes #", so it will auto close that issue when merged

**Comment by Likewise42** [comment]
Updated description as requested

**Comment by joshfinnie** [comment]
I heard some rumblings about the worry of someone scraping this endpoint. Have we thought of something like https://www.npmjs.com/package/express-rate-limit to help with that?

**Comment by dekkerglen** [comment]
@joshfinnie yes that's the way to go

**Comment by Likewise42** [comment]
Should we make a separate issue for that?

**Comment by dekkerglen** [comment]
I think adding that to this PR would be good. You can configure throttle rates on a per route basis, so just apply it to this one for now

**Pull request merged**
