### PR TITLE
Fixes for custom drafts:  UI, more feedback for filter errors, adfan...

### PR DESCRIPTION
**Pull request by RKelln**
- small fixes for custom draft UI
  - remove pack works again
  - can't remove last card in pack 
- check filters when saving a custom draft and show warnings if no cards for any of the filters
- change asfan custom draft code to use separate functions rather than polluting existing
  (note: quite likely I broke something, but code isn't being run yet)
- filterToString() help in Filter for turning parsed filters back into strings (not perfectly but close enough for warnings at this point)

### CODE REVIEW

**Comment by RKelln** [comment]
Err, wait, caught a few more little bugs with this.

**Comment by dekkerglen** [comment]
The 3rd bullet point stresses me out. Do you mean that those separate functions aren't in use yet anyway?

**Comment by RKelln** [comment]
Correct functions are defined but not called from anywhere yet.

**Comment by dekkerglen** [comment]
Is this ready to merge?

**Comment by RKelln** [comment]
Yup, lemme just change that one cube save call.

**Pull request merged**
