### PR TITLE
beautify public/js automatically

### PR DESCRIPTION
**Pull request by emmett9001**
This pull request adds `public/js` to the list of beautified directories.

### CODE REVIEW

**Comment by emmett9001** [comment]
@joshfinnie mind taking a look at this? I'm not certain whether you used the `beautify` or `js-beautify` npm module in https://github.com/dekkerglen/CubeCobra/pull/158.

**Comment by joshfinnie** [comment]
@emmett9001 I am installing `js-beautify` in the dev dependencies of the package.json here: https://github.com/dekkerglen/CubeCobra/blob/master/package.json#L45

I also purposefully excluded the `public` folder but on second look `public/js/**/.js` should be added to the script. I would modify the npm script (line 7 on package.json) to read `js-beautify --config .js-beautify.json -r *.js {config,models,routes,serverjs,views,public/js}/**/*.js` to incorporate that folder.

**Comment by emmett9001** [comment]
Fixed! Thanks for the pointer @joshfinnie

**Comment by joshfinnie** [comment]
np, nice find @emmett9001 !

**Pull request merged**
