### PR TITLE
Dr4ft export

### PR DESCRIPTION
**Pull request by thyeggman**
Adding a [dr4ft](https://dr4ft.info/) export option to cube decks.

TODO: test, add screenshot

Also did some refactoring of the deck export code to reduce it by a good chunk.

### CODE REVIEW

**Comment by dekkerglen** [comment]
Isn't dr4ft format the same as cockatrioce?

**Comment by thyeggman** [comment]
@dekkerglen Default is slightly different from what I can tell.  The cockatrice export uses `1 Lightning Bolt` but an export from the dr4ft site uses `1x Lightning Bolt`.  I still need to do testing to see if they're compatible.  It may well be that they are, but when implementing I trusted that the cockatrice format was correct, and the dr4ft format differed, so I wrote a new method.

As a side note, if they are compatible, would you prefer one menu item with `Cockatrice / dr4ft (.txt)`, or separate buttons?  I think they should still have their own routes even if the dr4ft one just calls the original cockatrice implementation

**Comment by dekkerglen** [comment]
I think leaving it cockatrice is fine. What's the use case for exporting a deck to dr4ft? To use their deckbuilder? 

Dr4ft now has the ability to import from CC using their UI. Dr4ft and cockatrice are also in the same ecosystem, for what that's worth.

**Comment by thyeggman** [comment]
Ah, it looks like I misunderstood #1358 ... The user was asking for dr4ft import, not export like the title says 😓

The dr4ft export format differs from what the CC importer expects, so I think that's just a matter of modifying the regex or whatever it uses (I haven't checked) to accept the `1x`

I can remove the dr4ft export if you think it's just bulk (or just update the UI with dr4ft / cockatrice if they're compatible), but I'll make this PR about the import.

**Pull request closed without merging**
