### PR TITLE
slightly shrink p1p1 image for discord

### PR DESCRIPTION
**Pull request by lane-eden**
addresses #1018

### CODE REVIEW

**Comment by dekkerglen** [comment]
Some CI failures, can you merge master in and get the Github actions checks going?

**Comment by joshfinnie** [comment]
I feel that these images should be programmatically compressed. 8mb seems huge for these images... I know I brought this up before, but what would y'all think about having some image compression addded?

**Comment by dekkerglen** [comment]
@joshfinnie we should address image compression in a separate PR

**Comment by joshfinnie** [comment]
Sounds good... I'll make an issue to help me remember!

**Pull request merged**
