### PR TITLE
mass edit remove colors

### PR DESCRIPTION
**Pull request by emmett9001**
This pull request fixes https://github.com/dekkerglen/CubeCobra/issues/161 by adding the ability to remove color identity from multiple cards simultaneously (that is, make the color identity colorless).

The semantics of the colorless checkbox are as follows:
If unset, it has no effect
If set when other colors are also set, it has no effect (example: R + U + C = RU)
If set when no other colors are set, it unsets the color identity of the selected cards (that is, it sets their color identity to colorless)

### CODE REVIEW

**Comment by emmett9001** [comment]
This is ready for review

**Comment by emmett9001** [comment]
Blocked by https://github.com/dekkerglen/CubeCobra/pull/171

**Comment by dekkerglen** [comment]
Can you rebase and commit for conflicts?

**Comment by emmett9001** [comment]
Merged master and resolved conflicts

**Comment by emmett9001** [comment]
Replaced by https://github.com/dekkerglen/CubeCobra/pull/179

**Pull request closed without merging**
